//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalName
    {
        public int ID { get; set; }
        public string Animal { get; set; }
        public Nullable<int> SendingPlayer_Id { get; set; }
        public Nullable<int> ReceivingPlayer_Id { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
    }
}
